"""Constants for the Hisense B544 integration."""

from homeassistant.const import Platform

DOMAIN = "hisense_b544"
PLATFORMS = (
    Platform.BINARY_SENSOR,
    Platform.CLIMATE,
    Platform.SENSOR,
    Platform.SWITCH,
)

CONF_DEVICE = "device"
CONF_BAUDRATE = "baudrate"
CONF_TRANSPORT = "transport"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_UNIT_ID = "unit_id"
CONF_NAME = "name"
CONF_MODEL = "model"

DEFAULT_BAUDRATE = 9600
DEFAULT_PORT = 502
DEFAULT_SCAN_INTERVAL = 5
MIN_SCAN_INTERVAL = 5
MAX_SCAN_INTERVAL = 3600
DEFAULT_NAME = "Hisense B544"
DEFAULT_MODEL = "B544(E)"
BAUDRATES = (9600, 19200, 38400)
TRANSPORT_SERIAL = "serial"
TRANSPORT_TCP = "tcp"
TRANSPORTS = (TRANSPORT_SERIAL, TRANSPORT_TCP)
MESSAGE_SPACING = 0.03

MIN_TEMPERATURE = 18
MAX_TEMPERATURE = 32
