name: Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install homeassistant 'modbus-connection[tmodbus]' pymodbus pytest pytest-asyncio coverage ruff
      - run: ruff check .
      - run: coverage run -m pytest
      - run: coverage report
