name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: pip install '.[test]'
      - run: ruff check .
      - run: ruff format --check .
      - run: coverage run -m pytest
      - run: coverage report
