name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: python -m venv .venv
      - run: .venv/bin/pip install '.[test]'
      - run: ./scripts/validate
        env:
          GITHUB_TOKEN: ${{ github.token }}
